../tb/top/stub_pkgs.sv
../rtl/i2c_pkg.sv
../rtl/i2c_reg_pkg.sv
../rtl/i2c_reg_top.sv
../rtl/i2c_fifos.sv
../rtl/i2c_fifo_sync_sram_adapter.sv
../rtl/i2c_bus_monitor.sv
../rtl/i2c_controller_fsm.sv
../rtl/i2c_target_fsm.sv
../rtl/i2c_core.sv
../rtl/i2c.sv
../tb/env/i2c_tb_pkg.sv
../tb/top/i2c_if.sv
../tb/top/tb_top.sv